apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "eg-app.fullname" . }}-config
  namespace: {{ .Values.environment.namespace }}
  labels:
    {{- include "eg-app.labels" . | nindent 4 }}
data:
  APP_ENV: {{ .Values.application.app.env | default "development" | quote }}
  GCP_REGION: {{ .Values.global.region | quote }}
  GCP_PROJECT: {{ .Values.global.project | quote }}
  CLUSTER_NAME: {{ .Values.global.cluster | quote }}
  {{- with .Values.application.config }}
  {{- toYaml . | nindent 2 }}
  {{- end }}