{{- if .Values.security.externalSecrets.enabled }}
{{- $esoApiVersion := include "eg-app.externalSecretsApiVersion" . | trim }}

{{- range .Values.security.externalSecrets.secrets }}
---
apiVersion: {{ $esoApiVersion }}
kind: ExternalSecret
metadata:
  name: {{ .secretName }}
  namespace: {{ $.Values.environment.namespace }}
  labels:
    {{- include "eg-app.labels" $ | nindent 4 }}
spec:
  refreshInterval: {{ $.Values.security.externalSecrets.refreshInterval | default "1h" }}
  secretStoreRef:
    name: {{ $.Values.security.externalSecrets.secretStoreRef.name }}
    kind: {{ $.Values.security.externalSecrets.secretStoreRef.kind }}
  target:
    name: {{ .secretName }}
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      metadata:
        labels:
          {{- include "eg-app.labels" $ | nindent 10 }}
  data:
    {{- range .data }}
    - secretKey: {{ .secretKey }}
      remoteRef:
        key: {{ .remoteRef.key }}
    {{- end }}
{{- end }}
{{- end }}