{{- if .Values.security.serviceAccount.create }}

{{- $sa := .Values.security.serviceAccount }}

apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $sa.name | default (include "eg-app.serviceAccountName" .) }}
  namespace: {{ .Values.environment.namespace }}
  labels:
    {{- include "eg-app.labels" . | nindent 4 }}

  {{- if $sa.annotations }}
  annotations:
    {{- toYaml $sa.annotations | nindent 4 }}
  {{- end }}

automountServiceAccountToken: {{ $sa.automountToken | default false }}

{{- with .Values.imagePullSecrets }}
imagePullSecrets:
  {{- toYaml . | nindent 2 }}
{{- end }}

{{- end }}