{{- if .Values.platform.hpa.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "eg-cms.fullname" . }}
  namespace: {{ .Values.environment.namespace }}
  labels:
    {{- include "eg-cms.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "eg-cms.fullname" . }}
  minReplicas: {{ .Values.platform.hpa.minReplicas | default 2 }}
  maxReplicas: {{ .Values.platform.hpa.maxReplicas | default 5 }}
  # revisionHistoryLimit: {{ .Values.platform.hpa.revisionHistoryLimit | default 3 }}
  metrics:
    {{- toYaml .Values.platform.hpa.metrics | nindent 4 }}
  {{- with .Values.platform.hpa.behavior }}
  behavior:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}