{{- if .Values.security.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "eg-cms.fullname" . }}
  namespace: {{ .Values.environment.namespace }}
  labels:
    {{- include "eg-cms.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "eg-cms.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
    - Egress
  {{- with .Values.security.networkPolicy.ingress }}
  ingress:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.security.networkPolicy.egress }}
  egress:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}