{{- if .Values.platform.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "eg-cms.fullname" . }}
  namespace: {{ .Values.environment.namespace }}
  labels:
    {{- include "eg-cms.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "eg-cms.selectorLabels" . | nindent 6 }}
  {{- if .Values.platform.podDisruptionBudget.maxUnavailable }}
  maxUnavailable: {{ .Values.platform.podDisruptionBudget.maxUnavailable }}
  {{- else }}
  minAvailable: {{ .Values.platform.podDisruptionBudget.minAvailable | default 1 }}
  {{- end }}
{{- end }}