{{- if .Values.volumes.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "eg-cms.fullname" . }}-uploads
  namespace: {{ .Values.environment.namespace }}
  labels:
    {{- include "eg-cms.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
    {{- with .Values.volumes.persistence.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  accessModes:
    - {{ .Values.volumes.persistence.accessMode }}
  storageClassName: {{ .Values.volumes.persistence.storageClass }}
  resources:
    requests:
      storage: {{ .Values.volumes.persistence.size }}
{{- end }}