apiVersion: v1
kind: Service
metadata:
  name: {{ include "eg-cms.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "eg-cms.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type | default "ClusterIp" }}
  selector:
    {{- include "eg-cms.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.service.port | default 1337 }}
      targetPort: {{ .Values.service.targetPort | default 1337 }}
      {{- if .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}