{{- if .Values.externalSecrets.enabled }}
{{- $esoApiVersion := include "eg-app.externalSecretsApiVersion" . | trim }}
apiVersion: {{ $esoApiVersion }}
kind: ClusterSecretStore
metadata:
  name: {{ .Values.externalSecrets.secretStoreRef.name }}
spec:
  provider:
    gcpsm:
      projectID: {{ .Values.global.project }}
      auth:
        workloadIdentity:
          clusterLocation: {{ .Values.global.region }}
          clusterName: {{ .Values.global.cluster }}
          serviceAccountRef:
            name: {{ .Values.externalSecrets.secretStoreRef.serviceAccountName }}
            namespace: {{ .Values.externalSecrets.secretStoreRef.serviceAccountNamespace }}
{{- end }}