apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "eg-app.fullname" . }}-config
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "eg-app.labels" . | nindent 4 }}
data:
  APP_ENV: {{ .Values.namespace | quote }}
  GCP_REGION: {{ .Values.global.region | quote }}
