{{- if .Values.externalSecrets.enabled }}
{{- $esoApiVersion := include "eg-app.externalSecretsApiVersion" . | trim }}
{{- range .Values.externalSecrets.secrets }}
---
apiVersion: {{ $esoApiVersion }}
kind: ExternalSecret
metadata:
  name: {{ .secretName }}
  namespace: {{ $.Values.namespace }}
  labels:
    {{- include "eg-app.labels" $ | nindent 4 }}
spec:
  refreshInterval: {{ $.Values.externalSecrets.refreshInterval }}
  secretStoreRef:
    name: {{ $.Values.externalSecrets.secretStoreRef.name }}
    kind: {{ $.Values.externalSecrets.secretStoreRef.kind }}
  target:
    name: {{ .secretName }}
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    {{- range .data }}
    - secretKey: {{ .secretKey }}
      remoteRef:
        key: {{ .remoteRef.key }}
    {{- end }}
{{- end }}
{{- end }}
