{{- $managedCertificate := .Values.managedCertificate | default dict }}
{{- if $managedCertificate.enabled }}
{{- $domains := $managedCertificate.domains }}
{{- if not $domains }}
{{- $domains = pluck "host" .Values.ingress.hosts }}
{{- end }}
apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: {{ include "eg-app.fullname" . }}-cert
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "eg-app.labels" . | nindent 4 }}
spec:
  domains:
    {{- range $domains }}
    - {{ . | quote }}
    {{- end }}
{{- end }}