apiVersion: v1
kind: Service
metadata:
  name: {{ include "eg-app.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "eg-app.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.service.annotations | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "eg-app.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
