apiVersion: v2
name: eg-cms
description: CMS — stateful, single GKE cluster
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - cms
  - gke
maintainers:
  - name: platform-team
    email: kreddy@rezovle.com
