#PROJECT DETAILS
global:
  project: enhanced-games-gc
  region: europe-west2
  cluster: eg-cluster

# ENVIRONMENT-SPECIFIC CONFIGURATION FOR DEV NAMESPACE
environment:
  namespace: ""
  labels:
    environment: ""
    team: enhanced-games
  
    
  namespaceLabels:
    environment:
    team: 
  
  namespaceAnnotations: {}

#APPLICATION CONFIGURATION
application:
  name: eg-cms
  replicaCount: ""

  image:
    repository: ""
    tag: ""
    pullPolicy: IfNotPresent

  app:
    port: 1337
    name: "cms"
    env: ""
    terminationGracePeriodSeconds: 60
  
  configMap:
    LOG_LEVEL: "debug"
    PORT: "1337"

  resources:
    requests:
      cpu: ""
      memory: ""
    limits:
      cpu: ""
      memory: ""
  
  probes:
    liveness:
      path: /admin
      initialDelaySeconds: ""
      periodSeconds: ""
      failureThreshold: ""
      timeoutSeconds: ""
    readiness:
      path: /admin
      initialDelaySeconds: ""
      periodSeconds: ""
      failureThreshold: ""
      timeoutSeconds: 5
    startup:
      path: /admin
      failureThreshold: ""
      periodSeconds: ""


# NETWORK CONFIGURATION
networking:
  service:
    type: ClusterIP
    port: 1337
    targetPort: 1337
    annotations:
      cloud.google.com/neg: '{"ingress": true}'
      cloud.google.com/backend-config: ''

# SECURITY CONFIGURATION
security:
  serviceAccount:
    create: false
    name: gke-workload-sa
    automountToken: false
    annotations:
      iam.gke.io/gcp-service-account: eg-workload-sa@enhanced-games-gc.iam.gserviceaccount.com

  networkPolicy:
    enabled: false
  
  externalSecrets:
    enabled: true
    createSecretStore: false
    secretStoreRef:
      name: ""
      kind: ClusterSecretStore
      serviceAccountName: gke-workload-sa
      serviceAccountNamespace: ""
  
  envFromSecrets: 
    - secretName: ""
  
  
backendConfig:
  enabled: true
  securityPolicy:
    enabled: true
    name: ""
  healthCheck:
    enabled: true
    checkIntervalSec: 15
    timeoutSec: 5
    healthyThreshold: 1
    unhealthyThreshold: 2
    port: 1337
    type: HTTP
    requestPath: "/admin"
  sessionAffinity:
    enabled: false
    affinityType: "GENERATED_COOKIE"
    affinityCookieTtlSec: 3600
  connectionDraining:
    enabled: true
    drainingTimeoutSec: 60
  cdn:
      enabled: false
      cachePolicy:
        includeHost: true
        includeProtocol: true
        includeQueryString: false
      cacheMode: CACHE_ALL_STATIC
      defaultTtl: 3600
      maxTtl: 86400
      negativeCaching: true

# PLATFORM CONFIGURATION
platform:
  deployment:
    revisionHistoryLimit: ""

  podDisruptionBudget:
    enabled: false
    minAvailable: ''

  hpa:
    enabled: true
    minReplicas: ""
    maxReplicas: ""
    revisionHistoryLimit: ""
    metrics:
      - type: Resource
        resource:
          name: cpu
          target:
            type: Utilization
            averageUtilization: 65
      - type: Resource
        resource:
          name: memory
          target:
            type: Utilization
            averageUtilization: 75
    behavior:
      scaleUp:
        stabilizationWindowSeconds: 60
        selectPolicy: Max
        policies:
          - type: Percent
            value: 100
            periodSeconds: 60
          - type: Pods
            value: 2
            periodSeconds: 60
      scaleDown:
        stabilizationWindowSeconds: 300
        selectPolicy: Max
        policies:
          - type: Percent
            value: 50
            periodSeconds: 60
          - type: Pods
            value: 1
            periodSeconds: 120


# POD CONFIGURATION
pod:
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000
    runAsGroup: 1000
    fsGroup: 1000
    seccompProfile:
      type: RuntimeDefault
  
  containerSecurityContext:
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: false
    runAsNonRoot: true
    runAsUser: 1000
    capabilities:
      drop:
  
  nodeSelector:
    cloud.google.com/gke-nodepool: ""

  tolerations:
    - key: "environment"
      operator: "Equal"
      value: ""
      effect: ""

  podDisruptionBudget:
    enabled: false
  
  podAnnotations:
    cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
    prometheus.io/scrape: "true"
    prometheus.io/port: "1337"
    prometheus.io/path: "/metrics"




# CONFIGMAP  VALUES
configMap:
  DATABASE_CLIENT: ""
  DATABASE_HOST: ""
  DATABASE_PORT: ""
  DATABASE_NAME: ""
  DATABASE_USERNAME: ""
  DATABASE_SSL: ""
  DATABASE_SSL_REJECT_UNAUTHORIZED: ""
  NODE_TLS_REJECT_UNAUTHORIZED: ""
  GCS_BUCKET_NAME: ""
  LOG_LEVEL: "debug"
  PORT: "1337"
  


  





# VOLUME CONFIGURATION
volumes:
  persistence:
    enabled: false
    mountPath: ""
    size: ""
    storageClass: ""
    accessMode: ReadWriteOnce






















